apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack
data:
  init.sh: |
    #!/bin/sh

    # Cribl s3 input requires all object create events to be sent to sqs
    _SQS_NOTIFICATION_CONFIG=$( cat <<NOTIFCONFIG
    {
      "QueueConfigurations": [
        {
          "QueueArn": "arn:aws:sqs:us-east-1:000000000000:cribl",
          "Events": [
            "s3:ObjectCreated:*"
          ]
        }
      ]
    }
    NOTIFCONFIG
    )

    # exporting aws defaults, so we don't have to use them on each line
    export AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1

    aws --endpoint-url=http://localhost:4566 s3 mb s3://cribl
    aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name cribl
    aws --endpoint-url=http://localhost:4566 s3api put-bucket-notification-configuration --bucket cribl --notification-configuration "$_SQS_NOTIFICATION_CONFIG"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: app
        image: localstack/localstack:0.12.12
        ports:
        - containerPort: 4566
        env:
        - name: DATA_DIR
          value: /tmp/localstack/data
        - name: INIT_SCRIPTS_PATH
          value: /config
        - name: SERVICES
          value: s3,sqs
        # Add aws key, secret, and region, so local aws cli commands are easier
        - name: AWS_ACCESS_KEY_ID
          value: test
        - name: AWS_SECRET_ACCESS_KEY
          value: test
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - name: config
        configMap:
          name: localstack
          items:
          - key: init.sh
            path: init.sh
            mode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: sqs
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4566

---
apiVersion: v1
kind: Service
metadata:
  name: s3
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4566
